language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5

cache:
  directories:
    - spec/integrations/rails_4_2/test/node_modules
    - spec/integrations/rails_4_2/vendor/bundle

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential patch ruby-dev zlib1g-dev liblzma-dev libxml2-dev
