version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.4.1-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run: sudo apt-get update && sudo apt-get install -y build-essential patch ruby-dev zlib1g-dev liblzma-dev libgmp-dev


      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

#      # Restore bundle cache
#      - restore_cache:
#          keys:
#            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
#            - rails-demo-bundle-v2-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

#      # Store bundle cache
#      - save_cache:
#          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
#          paths:
#            - vendor/bundle

      - run:
          name: run
          command: bundle exec rake

      - run:
          name: Test generator on rails 4.2
          command: ./spec/integrations/rails_4_2/test.sh
      # Save test results for timing analysis
#      - store_test_results:
#          path: test_results